# Basic
title: 郑璟泓
subtitle: 个人站
description: 保持理智 相信未来
# 头像里面的标题
avatarTitle: Deep Zheng
# 头像里面的描述
avatarDesc: 什么都不会
#url: ""

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
    #valine:
    #    el: '#comment'
    #    enable: true
    #    appid: mdY50s5ByJYIg98RP6YM38gb-9Nh9j0Va
     #   appkey: 2h90kQfmYL7Au8Ap0mcfrMaz
    #    notify: false
    #    vefify: false
    #    placeholder: qwq 老铁，说两句呗
    #    avatar: wavatar
     #   guest_info: nick,mail
    #    pageSize: 10
# Social
social:
    #weibo: 
    github: deepzheng
    qq: 871121301
    # zhihu: 
    # juejin: xxx
    #jianshu: 
    # twitter: 
    mail: deepzheng@hust.edu.cn


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-84134159-3  
    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    #- {title: 技术支持, description: support, url: '/support'}      
    - {title: 关于我, description: about, url: '/about'}   
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


